# Generated by Django 4.1 on 2022-08-20 10:41

from django.db import migrations, models
import helpers


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_postjob_qualification_alter_competence_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='postjob',
            name='profile',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='postjob',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
