# Generated by Django 4.1 on 2022-08-22 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_alter_postjob_description_alter_postjob_max_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjob',
            name='profile',
        ),
        migrations.AddField(
            model_name='postjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
