# Generated by Django 4.1 on 2022-08-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_postjob_profile_postjob_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_experience',
            name='main_job',
            field=models.CharField(choices=[('Paint', 'Paint'), ('Electricity', 'Electricity'), ('Plumbing', 'Plumbing'), ('Industriel automation', 'Industriel automation'), ('Web developer', 'Web developer'), ('truck driver', 'truck driver')], max_length=100, null=True),
        ),
    ]
