# Generated by Django 4.1 on 2022-08-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_personal_experience_main_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_experience',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personal_experience',
            name='experience',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal_experience',
            name='main_job',
            field=models.CharField(blank=True, choices=[('Paint', 'Paint'), ('Electricity', 'Electricity'), ('Plumbing', 'Plumbing'), ('Industriel automation', 'Industriel automation'), ('Web developer', 'Web developer'), ('truck driver', 'truck driver')], default=None, max_length=100, null=True),
        ),
    ]
