# Generated by Django 4.1 on 2022-09-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_personal_experience_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='adress',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
