# Generated by Django 4.1 on 2022-09-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_postjob_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_experience',
            name='competence',
            field=models.ManyToManyField(blank=True, null=True, to='website.competence'),
        ),
    ]
