# Generated by Django 4.1 on 2022-09-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_experience',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
