# Generated by Django 4.1 on 2022-09-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_personal_experience_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjob',
            name='code',
        ),
        migrations.RemoveField(
            model_name='postjob',
            name='freq',
        ),
        migrations.AlterField(
            model_name='personal_experience',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personal_experience',
            name='experience',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
