# Generated by Django 4.0.3 on 2022-09-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='imagesfive',
            new_name='imagefive',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='imagessix',
            new_name='imagesix',
        ),
    ]
