# Generated by Django 4.0.3 on 2022-09-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_rename_imagesfive_category_imagefive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='imagefive',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='imagefour',
        ),
        migrations.RemoveField(
            model_name='category',
            name='imageone',
        ),
        migrations.RemoveField(
            model_name='category',
            name='imagesix',
        ),
        migrations.RemoveField(
            model_name='category',
            name='imagethree',
        ),
        migrations.RemoveField(
            model_name='category',
            name='imagetwo',
        ),
    ]
