# Generated by Django 4.0.3 on 2022-09-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_rename_imagefive_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
