# Generated by Django 4.0.3 on 2022-09-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
